version: '3.8'

services:
  sirius-strapi-backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: sirius-strapi-backend-dev:0.0.1
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: './.tmp/data.db'
    command: yarn develop
